### ISSUE TITLE
Add remarkable-tablet topic to the repo

### ISSUE THREAD

**Issue by Ameb** [LinusCDE/rmTabletDriver#1]
Hello. 

Please add the `remarkable-tablet` topic to the repo so it is easier to [find](https://github.com/topics/remarkable-tablet)

[Github help on topics](https://help.github.com/en/articles/classifying-your-repository-with-topics)

Thank you!

**Comment by LinusCDE** [comment]
Thanks.
I had completly forgotten that.

I've added the topic on my other reMarkable related repos as well.

**Comment by LinusCDE** [comment]
I also had forgotten to add it to your repo (I wasn't sure if it was finished yet, considering that it doesn't work with libinput where I seemingly can't find a fix).

Thanks to @StachuDotNet for adding it already.
